### ISSUE TITLE
schedule.py should allow non-DESI tiles

### ISSUE THREAD

**Issue by moustakas** [desihub/desisurvey#82]
`desisurvey.schedule` assumes that all tiles have `IN_DESI==1` (see [here](https://github.com/desihub/desisurvey/blob/master/py/desisurvey/schedule.py#L598)) but for Survey Validation mock-ups (and perhaps Survey Validation itself) it would be convenient if there was an option of using non-DESI tiles / pointings.

**Comment by sbailey** [comment]
The tiles file to use is specified in the desisurvey `config.yaml` file, which has a default of `py/desisurvey/data/config.yaml`, but can be specified via the `--config-file` option to `surveyplan` and `surveyinit`.  You could create an `sv-tiles.fits` file with your custom tiles using `IN_DESI=1` for all those tiles, and use a custom desisurvey `config.yaml` to point to that custom tiles file.  If that file is in `$DESIMODEL/data/footprint/` then you don't have to specify the path, otherwise (I think) you can put it anywhere if you include the full path in the desisurvey `config.yaml` file.

i.e. is the real requirement to be able to use IN_DESI=0 tiles in `desi-tiles.fits`, or rather is the requirement to be able to use arbitrary tiles files?  I think the latter is more flexible and already supported (albeit via config file alternations rather than command line options).  Does that provide the functionality that you need?  (and if not, why not?)

**Comment by sbailey** [comment]
For now I propose that we keep SV tiles out of desi-tiles.fits (i.e. a separate file) and use IN_DESI=1 so that we can point the config files at them and run with it.  i.e. "IN_DESI=1" becomes a statement about footprint, not about main-survey vs. other programs.

Previously I had thought that we would then merge those tiles into desi-tiles.fits under a different PROGRAM name, but this thread highlights that that could be problematic if we retain IN_DESI=1 since we don't want the main survey to try scheduling them.  Eventually survey* code could have an option for which PROGRAM values to consider, so that they could use the separate or merged tiles files.

**Comment by schlafly** [comment]
Closing this as we are now through SV.
