### ISSUE TITLE
allow programs other than DARK, GRAY, BRIGHT

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#84]
There are several places throughout desisurvey that hardcode the known programs to be 'DARK', 'GRAY', or 'BRIGHT'.  We may need more flexibility for commissioning and SV.  Consider generalizing this so that the set of programs used is derived from the programs listed in the config.yaml file (which should also be a superset of the programs in the input tiles file).

This could get tricky, so if it starts taking a lot of time or complexity, re-evaluate whether this flexibility is really needed.

Related to PR #83 .

**Comment by dkirkby** [comment]
Thinking about this a bit more, the scheduler associates DARK/GRAY/BRIGHT with corresponding cuts on the sun & moon parameters, so these program names are effectively predefined in the code and used to ensure that a DARK tile is not observed when the moon is up, etc.

I can think of two possible SV scenarios that would require new program definitions:
 - There are some SV tiles that should be scheduled independently of the moon (and sun?) parameters.
 - There are some SV tiles that care about sun/moon params, but with different boundaries than the main survey.

Does either of these apply to SV?  Otherwise, can someone describe the SV use case where you wouldn't want to label tiles using DARK/GRAY/BRIGHT?

**Comment by dkirkby** [comment]
Closing this with the "wontfix" label since the current `desisurvey.tiles.Tiles` assumptions should be sufficiently general to support SV.  Please reopen with any new info.
