### ISSUE TITLE
Add optional calls to fiberassignment

### ISSUE THREAD

**Issue by dkirkby** [desihub/desisurvey#93]
The normal interaction between the scheduler and fiber assignment is:

1. Run once after the target catalog is finalized and before the survey starts, and assign fibers to all tiles that could be scheduled on the first night (i.e., tiles in DARK-0, GRAY-4 or any BRIGHT pass).

2. Run during each full moon break to assign fibers to tiles whose "covering tiles" have been observed. The set of tiles to assign each full month is not known in advance since it depends on an actual observing conditions and survey progress.

With this scheme, each tile has fibers assigned during exactly one pass, but which tiles are assigned in which pass is stochastic (except for the initial pass).

This issue is to update the `surveyinit` and `afternoonplan` entry points to optionally invoke fiber assignment with the appropriate list of tile IDs.

This should wait until desihub/fiberassign#153 is merged.

Do we need to have a real target catalog to test this, or could something simple be mocked up on the fly to exercise the fiberassign algorithms in this mode?

**Comment by sbailey** [comment]
Comment: We definitely want `surveyinit` and `afternoonplan` to output what list of tiles should be fiberassigned at the next opportunity, but we don't *need* those codes to actually invoke `fiberassign` automatically.  I'm not even sure we *want* that.  e.g. even if we move `fiberassign` from NERSC to KPNO and make it completely automated, I'd rather see that happen as a wrapper cronjob script (run `afternoonplan` then run `fiberassign`) instead of coupling the two such that `afternoonplan` itself has to know how to call `fiberassign`).  Maybe this is just aesthetics, but it smells like an unnecessary coupling.

**Comment by schlafly** [comment]
This is deprecated as we plan to move to fiberassign-on-the-fly.
